# Use caffe and test barrista.
env:
  matrix:
    - WITH_CUDA=false WITH_CMAKE=false WITH_IO=true PYTHON_VERSION=2
    - WITH_CUDA=false WITH_CMAKE=false WITH_IO=true PYTHON_VERSION=3

language: cpp

cache:
  apt: true
  directories:
  - /home/travis/miniconda
  - /home/travis/miniconda2
  - /home/travis/miniconda3

compiler: gcc

before_install:
  - git clone https://github.com/BVLC/caffe.git
  - cd caffe
  - export CAFFE_PYTHON_FOLDER=${pwd}/python
  - export CAFFE_BIN_FOLDER=${pwd}/build_release/tools
  - echo $CAFFE_PYTHON_FOLDER
  - echo $CAFFE_BIN_FOLDER
  - git checkout 6eae122a8eb84f8371dde815986cd7524fc4cbaa
  - export NUM_THREADS=2
  - export SCRIPTS=./scripts/travis
  - export CONDA_DIR="/home/travis/miniconda$PYTHON_VERSION"

install:
  - sudo -E $SCRIPTS/travis_install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:$CONDA_DIR/lib
  - export PATH=$CONDA_DIR/bin:$CONDA_DIR/scripts:$PATH
  - sudo -E $CONDA_DIR/bin/conda install --yes opencv || true
  - sudo -E $CONDA_DIR/bin/conda install --yes scikit-image scikit-learn pylint
  - sudo -E $CONDA_DIR/bin/pip install --upgrade pip
  - sudo -E $CONDA_DIR/bin/pip install progressbar2
  - $SCRIPTS/travis_setup_makefile_config.sh
  - export CPU_ONLY=1
  - export USE_LMDB=1
  - export USE_LEVELDB=1
  - export USE_OPENCV=1

script:
  - make --jobs=$NUM_THREADS --keep-going all pycaffe
  - cd ..
  - python tests.py
  - pylint --disable=star-args,no-member barrista
  - pylint --disable=star-args,no-member example.py
  - pylint --disable=star-args,no-member setup.py
  - pylint --disable=star-args,no-member tests.py
