# Use caffe and test barrista.
env:
  matrix:
    - WITH_CUDA=false WITH_CMAKE=false WITH_IO=true PYTHON_VERSION=2
    - WITH_CUDA=false WITH_CMAKE=false WITH_IO=true PYTHON_VERSION=3

language: cpp

cache:
  apt: true
  directories:
  - /home/travis/miniconda
  - /home/travis/miniconda2
  - /home/travis/miniconda3

compiler: gcc

before_install:
  - git clone https://github.com/BVLC/caffe.git
  - cd caffe
  - git checkout 6eae122a8eb84f8371dde815986cd7524fc4cbaa
  - export NUM_THREADS=2
  - export SCRIPTS=./scripts/travis
  - export CONDA_DIR="/home/travis/miniconda$PYTHON_VERSION"

install:
  - sudo -E $SCRIPTS/travis_install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:$CONDA_DIR/lib
  - export PATH=$CONDA_DIR/bin:$PATH
  - sudo -E conda install opencv progressbar scikit-image scikit-learn
  - $SCRIPTS/travis_setup_makefile_config.sh
  - export CPU_ONLY=1
  - export USE_LMDB=1
  - export USE_LEVELDB=1
  - export USE_OPENCV=1
  - export CAFFE_PYTHON_FOLDER=/home/travis/caffe/python
  - export CAFFE_BIN_FOLDER=/home/travis/caffe/build_release/tools

script:
  - make --jobs=$NUM_THREADS --keep-going all pycaffe
  - cd ..
  - python setup.py tests
  - pylint barrista
  - pylint example.py
  - pylint setup.py
  - pylint tests.py
